// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrnteznzrunqueizeomi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxybnRlem56cnVucXVlaXplb21pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MjIzOTAsImV4cCI6MjA1NzI5ODM5MH0.oJIVQG28zLCArzERjIlf8m9ZUNLQWCEItGbJXPHwEw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);